services:
  db:
    image: postgres:18-alpine3.22
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: restaurant
    ports:
      - "5432:5432"
